In [ ]:
import pandas as pd
df = pd.read_csv('/Users/alexcarr/Desktop/SA Grind/2025_hitter_stats.csv')

In [11]:
df.head()

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,Rbat+,TB,GIDP,HBP,SH,SF,IBB,Pos,Awards,Player-additional
0,1.0,Francisco Lindor#,31.0,NYM,NL,5.9,160.0,732.0,644.0,117.0,...,128.0,300.0,9.0,16.0,0.0,7.0,2.0,*6/DH,ASMVP-10,lindofr01
1,2.0,Rafael Devers*,28.0,2TM,2LG,4.1,163.0,729.0,607.0,99.0,...,139.0,291.0,16.0,6.0,0.0,4.0,10.0,*D3/5H,NaN,deverra01
2,2.0,Rafael Devers*,28.0,BOS,AL,2.3,73.0,334.0,272.0,47.0,...,153.0,137.0,7.0,4.0,0.0,2.0,7.0,D,NaN,deverra01
3,2.0,Rafael Devers*,28.0,SFG,NL,1.9,90.0,395.0,335.0,52.0,...,127.0,154.0,9.0,2.0,0.0,2.0,3.0,D3/5H,NaN,deverra01
4,3.0,Shohei Ohtani*,30.0,LAD,NL,6.6,158.0,727.0,611.0,146.0,...,175.0,380.0,9.0,3.0,0.0,2.0,20.0,*D1,ASMVP-1SS,ohtansh01

In [12]:
df.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Lg', 'WAR', 'G', 'PA', 'AB', 'R', 'H',
       '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG',
       'OPS', 'OPS+', 'rOBA', 'Rbat+', 'TB', 'GIDP', 'HBP', 'SH', 'SF', 'IBB',
       'Pos', 'Awards', 'Player-additional'],
      dtype='str')

In [13]:
df.describe()

,Rk,Age,WAR,G,PA,AB,R,H,2B,3B,...,OPS,OPS+,rOBA,Rbat+,TB,GIDP,HBP,SH,SF,IBB
count,922.000000,922.000000,922.000000,922.000000,922.000000,922.000000,922.000000,922.000000,922.000000,922.00000,...,831.000000,831.000000,831.000000,831.000000,922.000000,922.000000,922.000000,922.000000,922.000000,922.000000
mean,377.392625,28.183297,0.681453,61.578091,218.991323,195.917570,25.704989,47.838395,9.234273,0.72885,...,0.619158,72.948255,0.279578,71.675090,78.557484,3.750542,2.329718,0.683297,1.565076,0.650759
std,212.740859,3.559945,1.515892,52.365239,216.435936,192.951243,28.253962,50.756780,10.164948,1.51726,...,0.207792,57.240065,0.086222,63.353495,86.711770,4.472697,3.331775,1.505517,2.067429,2.137902
min,1.000000,20.000000,-1.800000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,-100.000000,-0.035000,-333.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,193.250000,26.000000,-0.200000,13.250000,31.000000,29.000000,2.000000,4.000000,1.000000,0.00000,...,0.536000,52.000000,0.250500,51.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,381.500000,28.000000,0.100000,48.000000,136.500000,123.000000,14.000000,27.000000,5.000000,0.00000,...,0.649000,81.000000,0.293000,82.000000,43.000000,2.000000,1.000000,0.000000,1.000000,0.000000
75%,554.750000,30.000000,1.100000,107.750000,387.750000,344.000000,43.750000,83.750000,16.000000,1.00000,...,0.740000,106.000000,0.329000,108.000000,135.000000,6.000000,3.000000,1.000000,2.000000,0.000000
max,763.000000,41.000000,9.700000,163.000000,732.000000,652.000000,146.000000,184.000000,47.000000,17.00000,...,2.000000,466.000000,0.901000,536.000000,380.000000,31.000000,27.000000,13.000000,12.000000,36.000000